### ISSUE TITLE
cannot run？

### ISSUE THREAD

**Issue by whoisme007** [corpnewt/CleanDock#1]
Excuse me, why cannot run the CleanDock?
$ /Volumes/Data/Macdata/CleanDock-master/CleanDock.command ; exit;
Found 9 dock entries.
Iterating...
Traceback (most recent call last):
  File "/Volumes/Data/Macdata/CleanDock-master/CleanDock.command", line 80, in <module>
    c.main()
  File "/Volumes/Data/Macdata/CleanDock-master/CleanDock.command", line 60, in main
    print("{} not in allowed - removing...".format(x["tile-data"]["file-label"]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

**Comment by corpnewt** [comment]
Looks like there's some non-asciii chars in one of your file labels and it's bailing when trying to print it to the terminal. I can look later today and see if there's a way around that.

**Comment by whoisme007** [comment]
$ /Volumes/Data/Macdata/
under my folder, the lilu-and-friends ,the GenSmbios is OK,and I try to put CleanDock into /User/john/Downloads ,the result is same……

**Comment by corpnewt** [comment]
I know this is a bit late - but do give it another try.  I think I found the issue in the plist.py module while working with another script.

**Comment by whoisme007** [comment]
Last login: Tue Oct  9 12:43:03 on ttys000
/Volumes/Data/CleanDock-master/CleanDock.command ; exit;

# john @ johndeiMac in ~ [12:43:24] 
$ /Volumes/Data/CleanDock-master/CleanDock.command ; exit;
Found 8 dock entries.
Iterating...
Traceback (most recent call last):
  File "/Volumes/Data/CleanDock-master/CleanDock.command", line 80, in <module>
    c.main()
  File "/Volumes/Data/CleanDock-master/CleanDock.command", line 60, in main
    print("{} not in allowed - removing...".format(x["tile-data"]["file-label"]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
